--- Makefile.orig	2021-08-29 12:00:39.067000000 +1000
+++ Makefile	2021-08-29 13:36:47.068374981 +1000
@@ -42,21 +42,27 @@
 
 include Makefile.inc
 
+FPIC =
+ifeq ($(LIBEXT), .so)
+	FPIC = -fPIC
+endif
+
 prerequisites: Makefile.inc $(LIBSEQNEEDED) $(libdir)/libpord$(PLAT)$(LIBEXT)
 
 # dummy MPI library (sequential version)
 
 libseqneeded:
 	(cd libseq; $(MAKE))
+	cp libseq/libmpiseq$(PLAT)$(LIBEXT) lib/
 
 # Build the libpord.a library and copy it into $(topdir)/lib
 $(libdir)/libpord$(PLAT)$(LIBEXT):
 	if [ "$(LPORDDIR)" != "" ] ; then \
 	  cd $(LPORDDIR); \
-	  $(MAKE) CC="$(CC)" CFLAGS="$(OPTC)" AR="$(AR)" RANLIB="$(RANLIB)" OUTC="$(OUTC)" LIBEXT=$(LIBEXT); \
+	  $(MAKE) CC="$(CC)" CFLAGS="$(OPTC)" AR="$(AR)" RANLIB="$(RANLIB)" OUTC="$(OUTC)" PLAT="$(PLAT)" LIBEXT=$(LIBEXT); \
 	fi;
 	if [ "$(LPORDDIR)" != "" ] ; then \
-	  cp $(LPORDDIR)/libpord$(LIBEXT) $@; \
+	  cp $(LPORDDIR)/libpord$(PLAT)$(LIBEXT) $@; \
 	fi;
 
 clean:
