--- Makefile.orig	2021-08-29 13:08:23.862118940 +1000
+++ Makefile	2021-08-29 13:15:32.588736425 +1000
@@ -7,6 +7,10 @@
 # RANLIB must be passed to make.
 #
 
+ifeq ($(LIBEXT), .so)
+	FPIC=-fPIC
+endif
+
 INCLUDES = -I../include
 
 COPTIONS = $(INCLUDES) $(CFLAGS) $(OPTFLAGS)
@@ -22,14 +26,18 @@
 # OUTC = -o
 
 .c.o:
-	$(CC) $(COPTIONS) -c $*.c $(OUTC)$*.o
+	$(CC) $(COPTIONS) $(FPIC) -c $*.c $(OUTC)$*.o
 
-libpord$(LIBEXT):$(OBJS)
+libpord$(PLAT)$(LIBEXT):$(OBJS)
+ifeq ($(LIBEXT), .so)
+	$(CC) -shared $(OBJS) -Wl,-soname,libpord$(PLAT).so -o libpord$(PLAT).so -Wl,-z,defs
+else
 	$(AR)$@ $(OBJS)
 	$(RANLIB) $@
+endif
 
 clean:
 	rm -f *.o
 
 realclean:
-	rm -f *.o libpord.a
+	rm -f *.o libpord$(PLAT)$(LIBEXT)
