--- Makefile.orig	2021-08-29 10:58:47.920669904 +1000
+++ Makefile	2021-08-29 11:09:01.604369985 +1000
@@ -14,19 +14,24 @@
 all: $(incdir)/mumps_int_def.h libcommon s d c z
 
 libcommon: $(incdir)/mumps_int_def.h
-	$(MAKE) $(libdir)/libmumps_common$(PLAT)$(LIBEXT)
+	$(MAKE) $(libdir)/libmumps_common$(PLAT).a
+	$(MAKE) $(libdir)/libmumps_common$(PLAT).so
 
 s: $(incdir)/mumps_int_def.h libcommon
-	$(MAKE) ARITH=s $(libdir)/libsmumps$(PLAT)$(LIBEXT)
+	$(MAKE) ARITH=s $(libdir)/libsmumps$(PLAT).a
+	$(MAKE) ARITH=s $(libdir)/libsmumps$(PLAT).so
 
 d: $(incdir)/mumps_int_def.h libcommon
-	$(MAKE) ARITH=d $(libdir)/libdmumps$(PLAT)$(LIBEXT)
+	$(MAKE) ARITH=d $(libdir)/libdmumps$(PLAT).a
+	$(MAKE) ARITH=d $(libdir)/libdmumps$(PLAT).so
 
 c: $(incdir)/mumps_int_def.h libcommon
-	$(MAKE) ARITH=c $(libdir)/libcmumps$(PLAT)$(LIBEXT)
+	$(MAKE) ARITH=c $(libdir)/libcmumps$(PLAT).a
+	$(MAKE) ARITH=c $(libdir)/libcmumps$(PLAT).so
 
 z: $(incdir)/mumps_int_def.h libcommon
-	$(MAKE) ARITH=z $(libdir)/libzmumps$(PLAT)$(LIBEXT)
+	$(MAKE) ARITH=z $(libdir)/libzmumps$(PLAT).a
+	$(MAKE) ARITH=z $(libdir)/libzmumps$(PLAT).so
 
 include $(topdir)/Makefile.inc
 
@@ -192,14 +197,20 @@
         $(ARITH)tools.o\
         $(ARITH)type3_root.o
 
-$(libdir)/libmumps_common$(PLAT)$(LIBEXT):      $(OBJS_COMMON_MOD) $(OBJS_COMMON_OTHER)
-	$(AR)$@ $?
+$(libdir)/libmumps_common$(PLAT).a: $(OBJS_COMMON_MOD) $(OBJS_COMMON_OTHER)
+	$(AR) $@ $?
 	$(RANLIB) $@
 
-$(libdir)/lib$(ARITH)mumps$(PLAT)$(LIBEXT):    $(OBJS_MOD) $(OBJS_OTHER)
-	$(AR)$@ $?
+$(libdir)/lib$(ARITH)mumps$(PLAT).a: $(OBJS_MOD) $(OBJS_OTHER)
+	$(AR) $@ $?
 	$(RANLIB) $@
 
+$(libdir)/libmumps_common$(PLAT).so: $(OBJS_COMMON_MOD) $(OBJS_COMMON_OTHER)
+	$(FC) $(OPTL) -shared $^ -Wl,-soname,libmumps_common$(PLAT).so -L$(libdir) $(LORDERINGS) -lpthread $(MPIFLIB) $(MPICLIB) -o $(libdir)/libmumps_common$(PLAT).so -Wl,-z,defs
+
+$(libdir)/lib$(ARITH)mumps$(PLAT).so: $(OBJS_MOD) $(OBJS_OTHER)
+	$(FC) $(OPTL) -shared $^ -Wl,-soname,lib$(ARITH)mumps$(PLAT).so -L$(libdir) -lmumps_common$(PLAT) $(LORDERINGS) $(MPIFLIB) $(LIBBLAS) $(SCALAP) $(LAPACK) -o $(libdir)/lib$(ARITH)mumps$(PLAT).so -Wl,-z,defs
+
 # Dependencies between modules:
 # i) arithmetic-dependent modules:
 $(ARITH)ana_aux.o:              $(ARITH)mumps_struc_def.o \
@@ -411,13 +422,13 @@
 
 .SUFFIXES: .c .F .o
 .F.o:
-	$(FC) $(OPTF) -I. -I../include $(INCS) $(IORDERINGSF) $(ORDERINGSF) -c $*.F $(OUTF)$*.o
+	$(FC) $(OPTF) -I. -I../include $(INCS) $(IORDERINGSF) $(ORDERINGSF) -fPIC -c $*.F $(OUTF)$*.o
 .c.o:
-	$(CC) $(OPTC) -I../include $(INCS) $(CDEFS) $(IORDERINGSC) $(ORDERINGSC) -c $*.c $(OUTC)$*.o
+	$(CC) $(OPTC) -I../include $(INCS) $(CDEFS) $(IORDERINGSC) $(ORDERINGSC) -fPIC -c $*.c $(OUTC)$*.o
 
 $(ARITH)mumps_c.o:	mumps_c.c
 	$(CC) $(OPTC) -I../include $(INCS) $(CDEFS) -DMUMPS_ARITH=MUMPS_ARITH_$(ARITH) \
-	      $(IORDERINGSC) $(ORDERINGSC) -c mumps_c.c $(OUTC)$@
+	      $(IORDERINGSC) $(ORDERINGSC) -fPIC -c mumps_c.c $(OUTC)$@
 
 clean:
-	$(RM) *.o *.mod $(incdir)/mumps_int_def.h build_mumps_int_def
+	$(RM) *.o *.mod *.a *.so $(incdir)/mumps_int_def.h build_mumps_int_def
